const fs = require('fs');
const path = require('path');

const MCJARS_API = 'https://mcjars.app/api/v1';

const mcjars = {
  async getTypes() {
    try {
      const res = await fetch(`${MCJARS_API}/types`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      return data.types || {};
    } catch (err) {
      console.error('Error fetching mcjars types:', err.message);
      return {};
    }
  },

  async getBuilds(type = 'PAPER') {
    try {
      const res = await fetch(`${MCJARS_API}/builds/${encodeURIComponent(type.toUpperCase())}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      return data.versions || {};
    } catch (err) {
      console.error(`Error fetching mcjars builds for ${type}:`, err.message);
      return {};
    }
  },

  async getVersions(type = 'PAPER') {
    const versions = await this.getBuilds(type);
    return Object.keys(versions);
  },

  async getLatestBuild(type = 'PAPER', version = 'latest') {
    const versions = await this.getBuilds(type);
    const verKeys = Object.keys(versions);
    if (!verKeys.length) return null;

    let targetVer = version;
    if (version === 'latest' || !versions[version]) {
      targetVer = verKeys[verKeys.length - 1];
    }

    const versionData = versions[targetVer];
    if (!versionData || !versionData.latest) return null;

    return {
      version: targetVer,
      java: versionData.java || 21,
      buildNumber: versionData.latest.buildNumber,
      jarUrl: versionData.latest.jarUrl,
      jarSize: versionData.latest.jarSize,
      name: versionData.latest.name
    };
  },

  async installServerJar(type = 'PAPER', version = 'latest', targetDir) {
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    const build = await this.getLatestBuild(type, version);
    if (!build || !build.jarUrl) {
      throw new Error(`Could not find jar for ${type} version ${version}`);
    }

    console.log(`⬇️ Downloading ${type} ${build.version} (${build.jarUrl})...`);
    const jarResponse = await fetch(build.jarUrl);
    if (!jarResponse.ok) {
      throw new Error(`Failed to download server jar: HTTP ${jarResponse.status}`);
    }

    const arrayBuffer = await jarResponse.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const targetJarPath = path.join(targetDir, 'server.jar');
    fs.writeFileSync(targetJarPath, buffer);
    console.log(`✅ Saved server.jar to ${targetJarPath} (${(buffer.length / 1024 / 1024).toFixed(2)} MB)`);

    // Auto-accept EULA
    const eulaPath = path.join(targetDir, 'eula.txt');
    fs.writeFileSync(eulaPath, '# Generated by Nova Panel\neula=true\n');

    // Create default server.properties if not exists
    const serverPropsPath = path.join(targetDir, 'server.properties');
    if (!fs.existsSync(serverPropsPath)) {
      fs.writeFileSync(serverPropsPath, `# Minecraft server properties\n# Generated by Nova Panel\nmotd=A Nova Hosted Minecraft Server\nserver-port=25565\nonline-mode=false\n`);
    }

    return {
      type,
      version: build.version,
      java: build.java,
      jarPath: targetJarPath
    };
  }
};

module.exports = mcjars;
